### ISSUE TITLE
why it doesn't work

### ISSUE THREAD

**Issue by swithun-liu** [wafer-li/hexo-filter-plantuml#5]
![image](https://user-images.githubusercontent.com/42160297/81665964-f8877c00-9473-11ea-8896-2ed68d4c3740.png)

![image](https://user-images.githubusercontent.com/42160297/81665988-ffae8a00-9473-11ea-92fd-152e5740b48a.png)

in my vscode
![image](https://user-images.githubusercontent.com/42160297/81666028-0e953c80-9474-11ea-920a-9b7321cdcecf.png)

**Comment by miao1007** [comment]
try two space padding.
```yaml
plantuml:
  render: "PlantUMLServer"
  link: 'inlineBase64'
```
